server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    org.springframework: DEBUG
spring:
  messages:
    basename: messages
management:
  endpoints:
    web:
      exposure:
        include: "*"