server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    org.springframework: DEBUG
spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
management:
  endpoints:
    web:
      exposure:
        include: "*"